#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace UsersEntitiesModel	
{
	public partial class User
	{
		private string _userPassword;
		public virtual string UserPassword
		{
			get
			{
				return this._userPassword;
			}
			set
			{
				this._userPassword = value;
			}
		}
		
		private string _userName;
		public virtual string UserName
		{
			get
			{
				return this._userName;
			}
			set
			{
				this._userName = value;
			}
		}
		
		private int _userID;
		public virtual int UserID
		{
			get
			{
				return this._userID;
			}
			set
			{
				this._userID = value;
			}
		}
		
		private string _userEmail;
		public virtual string UserEmail
		{
			get
			{
				return this._userEmail;
			}
			set
			{
				this._userEmail = value;
			}
		}
		
		private DateTime _lastActiveDate;
		public virtual DateTime LastActiveDate
		{
			get
			{
				return this._lastActiveDate;
			}
			set
			{
				this._lastActiveDate = value;
			}
		}
		
		private bool _isOnLine;
		public virtual bool IsOnLine
		{
			get
			{
				return this._isOnLine;
			}
			set
			{
				this._isOnLine = value;
			}
		}
		
	}
}
#pragma warning restore 1591
