#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using WebApplicationModel;

namespace WebApplicationModel	
{
	[System.Serializable()]
	public partial class Product : System.Runtime.Serialization.ISerializable
	{
		private int _productID;
		public virtual int ProductID
		{
			get
			{
				return this._productID;
			}
			set
			{
				this._productID = value;
			}
		}
		
		private string _productName;
		public virtual string ProductName
		{
			get
			{
				return this._productName;
			}
			set
			{
				this._productName = value;
			}
		}
		
		private int? _supplierID;
		public virtual int? SupplierID
		{
			get
			{
				return this._supplierID;
			}
			set
			{
				this._supplierID = value;
			}
		}
		
		private int? _categoryID;
		public virtual int? CategoryID
		{
			get
			{
				return this._categoryID;
			}
			set
			{
				this._categoryID = value;
			}
		}
		
		private string _quantityPerUnit;
		public virtual string QuantityPerUnit
		{
			get
			{
				return this._quantityPerUnit;
			}
			set
			{
				this._quantityPerUnit = value;
			}
		}
		
		private decimal? _unitPrice;
		public virtual decimal? UnitPrice
		{
			get
			{
				return this._unitPrice;
			}
			set
			{
				this._unitPrice = value;
			}
		}
		
		private short? _unitsInStock;
		public virtual short? UnitsInStock
		{
			get
			{
				return this._unitsInStock;
			}
			set
			{
				this._unitsInStock = value;
			}
		}
		
		private short? _unitsOnOrder;
		public virtual short? UnitsOnOrder
		{
			get
			{
				return this._unitsOnOrder;
			}
			set
			{
				this._unitsOnOrder = value;
			}
		}
		
		private short? _reorderLevel;
		public virtual short? ReorderLevel
		{
			get
			{
				return this._reorderLevel;
			}
			set
			{
				this._reorderLevel = value;
			}
		}
		
		private bool _discontinued;
		public virtual bool Discontinued
		{
			get
			{
				return this._discontinued;
			}
			set
			{
				this._discontinued = value;
			}
		}
		
		private Category _category;
		public virtual Category Category
		{
			get
			{
				return this._category;
			}
			set
			{
				this._category = value;
			}
		}
		
		#region ISerializable Implementation
		
		public Product()
		{
		}
		
		protected Product(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			this.ProductID = info.GetInt32("ProductID");
			this.ProductName = info.GetString("ProductName");
			this.SupplierID = (int?)info.GetValue("SupplierID", typeof(int?));
			this.CategoryID = (int?)info.GetValue("CategoryID", typeof(int?));
			this.QuantityPerUnit = info.GetString("QuantityPerUnit");
			this.UnitPrice = (decimal?)info.GetValue("UnitPrice", typeof(decimal?));
			this.UnitsInStock = (short?)info.GetValue("UnitsInStock", typeof(short?));
			this.UnitsOnOrder = (short?)info.GetValue("UnitsOnOrder", typeof(short?));
			this.ReorderLevel = (short?)info.GetValue("ReorderLevel", typeof(short?));
			this.Discontinued = info.GetBoolean("Discontinued");
			CustomizeDeserializationProcess(info, context);
		}
		
		public virtual void GetObjectData(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			info.AddValue("ProductID", this.ProductID, typeof(int));
			info.AddValue("ProductName", this.ProductName, typeof(string));
			info.AddValue("SupplierID", this.SupplierID, typeof(int?));
			info.AddValue("CategoryID", this.CategoryID, typeof(int?));
			info.AddValue("QuantityPerUnit", this.QuantityPerUnit, typeof(string));
			info.AddValue("UnitPrice", this.UnitPrice, typeof(decimal?));
			info.AddValue("UnitsInStock", this.UnitsInStock, typeof(short?));
			info.AddValue("UnitsOnOrder", this.UnitsOnOrder, typeof(short?));
			info.AddValue("ReorderLevel", this.ReorderLevel, typeof(short?));
			info.AddValue("Discontinued", this.Discontinued, typeof(bool));
			CustomizeSerializationProcess(info, context);
		}
		
		partial void CustomizeSerializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		partial void CustomizeDeserializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		#endregion
	}
}
#pragma warning restore 1591
