#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using PermissionsEntitiesModel;

namespace PermissionsEntitiesModel	
{
	public partial class PermissionsModel : OpenAccessContext, IPermissionsModelUnitOfWork
	{
		private static string connectionStringName = @"PermissionsConnection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("PermissionsModel.rlinq");
		
		public PermissionsModel()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public PermissionsModel(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public PermissionsModel(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public PermissionsModel(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public PermissionsModel(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<Permission> Permissions 
		{
			get
			{
				return this.GetAll<Permission>();
			}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "MsSql";
			backend.ProviderName = "System.Data.SqlClient";
			backend.Logging.MetricStoreSnapshotInterval = 0;
		
			CustomizeBackendConfiguration(ref backend);
		
			return backend;
		}
		
		/// <summary>
		/// Allows you to customize the BackendConfiguration of PermissionsModel.
		/// </summary>
		/// <param name="config">The BackendConfiguration of PermissionsModel.</param>
		static partial void CustomizeBackendConfiguration(ref BackendConfiguration config);
		
	}
	
	public interface IPermissionsModelUnitOfWork : IUnitOfWork
	{
		IQueryable<Permission> Permissions
		{
			get;
		}
	}
}
#pragma warning restore 1591
